import { useState, useEffect } from 'react';
import {
  ScaleIcon, SparklesIcon, ArrowDownTrayIcon, TrashIcon, ClockIcon, DocumentTextIcon,
  ExclamationTriangleIcon, CheckCircleIcon, LightBulbIcon,
} from '@heroicons/react/24/outline';
import { pcoReviewApi, payAppReviewApi } from '../api';
import PageHeader from '../components/PageHeader';
import FileDrop from '../components/FileDrop';

function money(n) {
  return typeof n === 'number' ? `$${n.toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 })}` : 'n/a';
}

// Findings grouped the same way the pay app report is: what blocks approval, what else
// is wrong, then — visually separated — the AI's advisory reading of the documents.
function PcoReportView({ report }) {
  const sectionCard = (title, items, tone) => {
    if (items.length === 0) return null;
    const styles = tone === 'critical'
      ? { border: '#fecaca', bg: '#fef2f2', heading: '#b91c1c', Icon: ExclamationTriangleIcon }
      : { border: '#fed7aa', bg: '#fff7ed', heading: '#c2410c', Icon: ExclamationTriangleIcon };
    return (
      <div className="card p-5 space-y-3" style={{ background: styles.bg, border: `1px solid ${styles.border}` }}>
        <h3 className="text-sm font-semibold flex items-center gap-2" style={{ color: styles.heading }}>
          <styles.Icon className="w-4 h-4" /> {title}
        </h3>
        {items.map((r, i) => (
          <div key={i}>
            <p className="text-sm font-medium text-gray-900">{r.description}</p>
            <p className="text-xs text-gray-600 mt-0.5">{r.detail}</p>
          </div>
        ))}
      </div>
    );
  };

  const o = report.observations || {};
  const notes = [
    o.scopeAlignment?.notes && { title: 'Does the price match what was asked for?', body: o.scopeAlignment.notes },
    o.lumpSumConcerns && { title: 'Lump sums worth a closer look', body: o.lumpSumConcerns },
    o.pricingSanity && { title: 'Pricing worth double-checking', body: o.pricingSanity },
  ].filter(Boolean);

  return (
    <div className="space-y-4">
      <div className="card p-5">
        <div className="flex items-baseline justify-between gap-3 flex-wrap">
          <h3 className="text-sm font-semibold text-gray-900">
            PCO {report.header.pcoNumber}{report.header.title ? ` — ${report.header.title}` : ''}
          </h3>
          <span className="text-lg font-semibold text-gray-900 tabular-nums">{money(report.header.totalAmount)}</span>
        </div>
        <p className="text-xs text-gray-400 mt-1">
          {report.header.contractor} · {report.header.date}
          {report.header.isAllowance ? ' · presented as an allowance' : ''}
          {report.header.reference?.number ? ` · generated by ${report.header.reference.type || ''} ${report.header.reference.number}` : ''}
        </p>
        <p className="text-sm text-gray-700 mt-3">{report.plainEnglish}</p>
      </div>

      {sectionCard('Issues to Resolve Before Approving', report.critical, 'critical')}
      {sectionCard('Other Problems Found', report.mathErrors, 'warn')}

      {notes.length > 0 && (
        <div className="card p-5 space-y-3" style={{ background: '#f5f3ff', border: '1px solid #ddd6fe' }}>
          <h3 className="text-sm font-semibold flex items-center gap-2" style={{ color: '#6d28d9' }}>
            <LightBulbIcon className="w-4 h-4" /> Review Notes — the AI's read, verify before acting
          </h3>
          {notes.map((n, i) => (
            <div key={i}>
              <p className="text-sm font-medium text-gray-900">{n.title}</p>
              <p className="text-xs text-gray-600 mt-0.5">{n.body}</p>
            </div>
          ))}
        </div>
      )}

      {report.cleanBill.length > 0 && (
        <div className="card p-5 space-y-2">
          <h3 className="text-sm font-semibold text-gray-900 flex items-center gap-2">
            <CheckCircleIcon className="w-4 h-4" style={{ color: '#059669' }} /> Everything Else Checked Out Fine
          </h3>
          {report.cleanBill.map((r, i) => (
            <p key={i} className="text-xs text-gray-500"><span className="font-medium text-gray-700">{r.description}</span> {r.detail}</p>
          ))}
        </div>
      )}

      {report.warnings.length > 0 && (
        <div className="card p-5 space-y-2">
          <h3 className="text-sm font-semibold text-gray-400">Checks We Couldn't Fully Complete</h3>
          {report.warnings.map((r, i) => (
            <p key={i} className="text-xs text-gray-400">{r.description} — {r.detail}</p>
          ))}
        </div>
      )}
    </div>
  );
}

function HistoryRow({ item, onView, onDelete }) {
  const date = new Date(item.created_at).toLocaleDateString('en-US', { month: 'short', day: 'numeric', year: 'numeric' });
  const badge = item.critical_count > 0
    ? { bg: '#fef2f2', color: '#b91c1c', text: `${item.critical_count} critical` }
    : item.fail_count > 0
      ? { bg: '#fff7ed', color: '#c2410c', text: `${item.fail_count} issue${item.fail_count === 1 ? '' : 's'}` }
      : { bg: '#d1fae5', color: '#065f46', text: 'Clean' };
  return (
    <div className="card px-5 py-3.5 flex items-center justify-between cursor-pointer" onClick={() => onView(item.id)}>
      <div className="flex items-center gap-3 min-w-0">
        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-[10px] font-semibold flex-shrink-0" style={{ background: badge.bg, color: badge.color }}>
          {badge.text}
        </span>
        <div className="min-w-0">
          <p className="text-sm font-medium text-gray-900 truncate">
            PCO {item.pco_number || '—'}{item.title ? ` — ${item.title}` : ''}
          </p>
          <p className="text-xs text-gray-400 mt-0.5">{money(item.total_amount)} · {item.contractor || '—'}</p>
        </div>
      </div>
      <div className="flex items-center gap-3 flex-shrink-0 ml-4">
        <span className="flex items-center gap-1 text-xs text-gray-400"><ClockIcon className="w-3.5 h-3.5" />{date}</span>
        <button className="btn-danger" onClick={e => { e.stopPropagation(); onDelete(item.id); }}><TrashIcon className="w-4 h-4" /></button>
      </div>
    </div>
  );
}

export default function PcoReview() {
  const [pcoFile, setPcoFile] = useState(null);
  const [referenceFile, setReferenceFile] = useState(null);
  const [isAllowance, setIsAllowance] = useState(false);

  const [projects, setProjects] = useState([]);
  const [projectId, setProjectId] = useState('');
  const [contract, setContract] = useState(null);

  const [analyzing, setAnalyzing] = useState(false);
  const [error, setError] = useState('');
  const [result, setResult] = useState(null);   // { id, report }
  const [viewing, setViewing] = useState(null); // { id, report }
  const [history, setHistory] = useState([]);

  const loadHistory = () => pcoReviewApi.list().then(setHistory);
  useEffect(() => { loadHistory(); payAppReviewApi.projects().then(setProjects); }, []);

  // The stored contract drives the tax / markup / unallowable checks, so surface
  // whether one is on file before the user runs anything.
  useEffect(() => {
    if (!projectId) { setContract(null); return; }
    let cancelled = false;
    payAppReviewApi.getContract(projectId)
      .then(d => { if (!cancelled) setContract(d); })
      .catch(() => { if (!cancelled) setContract(null); });
    return () => { cancelled = true; };
  }, [projectId]);

  const handleAnalyze = async () => {
    if (!pcoFile) { setError('Upload the PCO PDF first.'); return; }
    setError(''); setAnalyzing(true); setResult(null); setViewing(null);
    try {
      const fd = new FormData();
      fd.append('pco_file', pcoFile);
      if (referenceFile) fd.append('reference_file', referenceFile);
      if (projectId) fd.append('project_id', projectId);
      fd.append('is_allowance', String(isAllowance));
      const data = await pcoReviewApi.create(fd);
      setResult({ id: data.id, report: data.report });
      loadHistory();
    } catch (err) {
      setError(err.response?.data?.error || 'Could not analyze this PCO.');
    } finally {
      setAnalyzing(false);
    }
  };

  const handleView = async id => {
    const record = await pcoReviewApi.get(id);
    setResult(null);
    setViewing({ id: record.id, report: record.report });
  };

  const handleDelete = async id => {
    await pcoReviewApi.delete(id);
    if (viewing?.id === id) setViewing(null);
    if (result?.id === id) setResult(null);
    loadHistory();
  };

  const reset = () => { setPcoFile(null); setReferenceFile(null); setIsAllowance(false); setResult(null); setError(''); };
  const active = result || viewing;

  return (
    <div className="space-y-6">
      <PageHeader
        icon={ScaleIcon}
        iconGradient="linear-gradient(135deg, #f59e0b, #ef4444)"
        title="Change Order Review"
        subtitle="Upload a PCO and the RFI or ASI that generated it — get math, tax, and markup checks against the contract"
      />

      <div className="grid grid-cols-5 gap-6">
        <div className="col-span-2 space-y-4">
          <div className="card card-accent p-6 space-y-5" style={{ '--card-accent': 'linear-gradient(90deg, #f59e0b, #ef4444)' }}>
            <div className="flex items-center justify-between gap-2">
              <div className="flex items-center gap-2">
                <div className="w-7 h-7 rounded-lg flex items-center justify-center flex-shrink-0"
                  style={{ background: 'linear-gradient(135deg, #f59e0b, #ef4444)' }}>
                  <ScaleIcon className="w-4 h-4 text-white" />
                </div>
                <h2 className="text-sm font-semibold text-gray-900">New PCO Review</h2>
              </div>
              {(pcoFile || referenceFile || result) && (
                <button type="button" className="btn-secondary px-2.5 py-1 text-xs" onClick={reset}>Reset</button>
              )}
            </div>

            <div>
              <label className="label">Project</label>
              <select className="input" value={projectId} onChange={e => setProjectId(e.target.value)}>
                <option value="">Which project is this PCO for?</option>
                {projects.map(p => (
                  <option key={p.id} value={p.id}>{p.project_name}</option>
                ))}
              </select>
              {projectId && (
                <p className="text-xs mt-1" style={{ color: contract ? '#059669' : '#c2410c' }}>
                  {contract
                    ? `Contract on file (${contract.file_name}) — its tax and cost terms will be checked against this PCO.`
                    : 'No contract on file for this project — tax and unallowable-item checks will be limited. Upload one on the Pay App Review tab.'}
                </p>
              )}
            </div>

            <FileDrop file={pcoFile} onChange={setPcoFile} label="Potential Change Order (PDF) *" />
            <FileDrop file={referenceFile} onChange={setReferenceFile} label="RFI / ASI that generated it (PDF)" />

            <label className="flex items-start gap-2 cursor-pointer">
              <input type="checkbox" className="mt-0.5" checked={isAllowance} onChange={e => setIsAllowance(e.target.checked)} />
              <span className="text-xs text-gray-600">
                <span className="font-medium text-gray-900">This PCO is an allowance.</span> An allowance is the owner's
                set-aside money — the contractor may not take overhead and profit on it.
              </span>
            </label>

            {error && (
              <div className="p-3 rounded-xl text-sm" style={{ background: '#fef2f2', border: '1px solid #fecaca', color: '#b91c1c' }}>
                {error}
              </div>
            )}

            <button type="button" className="btn-primary w-full justify-center" onClick={handleAnalyze} disabled={analyzing || !pcoFile}>
              {analyzing ? (
                <><SparklesIcon className="w-4 h-4 animate-pulse" /> Reviewing…</>
              ) : (
                <><SparklesIcon className="w-4 h-4" /> Review Change Order</>
              )}
            </button>

            {!referenceFile && !result && (
              <p className="text-[11px] text-gray-400">
                Without the RFI or ASI, the review can't confirm the PCO prices only the work that was actually asked for.
              </p>
            )}
          </div>
        </div>

        <div className="col-span-3 space-y-4">
          {active && (
            <>
              <div className="flex items-center justify-between">
                <h2 className="text-sm font-semibold text-gray-900">{result ? 'Review Result' : 'Stored Review'}</h2>
                <div className="flex items-center gap-2">
                  <button className="btn-secondary px-3 py-1.5" onClick={() => pcoReviewApi.downloadMarkdown(active.id)}>
                    <DocumentTextIcon className="w-4 h-4" /> .md
                  </button>
                  <button className="btn-secondary px-3 py-1.5" onClick={() => pcoReviewApi.downloadOriginal(active.id)}>
                    <ArrowDownTrayIcon className="w-4 h-4" /> Original PDF
                  </button>
                  <button className="btn-secondary px-3 py-1.5" onClick={() => { setResult(null); setViewing(null); }}>Close</button>
                </div>
              </div>
              <PcoReportView report={active.report} />
            </>
          )}

          {!active && (
            <>
              <h2 className="text-sm font-semibold text-gray-900">Review History</h2>
              {history.length === 0 ? (
                <div className="card p-8 text-center text-sm text-gray-400">
                  No change orders reviewed yet. Upload a PCO to get started.
                </div>
              ) : (
                <div className="space-y-2">
                  {history.map(item => (
                    <HistoryRow key={item.id} item={item} onView={handleView} onDelete={handleDelete} />
                  ))}
                </div>
              )}
            </>
          )}
        </div>
      </div>
    </div>
  );
}
