const { money } = require('./payAppChecks');

// Assembles the PCO review into the same shape the pay app report uses: a plain-English
// summary, the deterministic findings grouped by severity, and — kept deliberately
// separate — the model's advisory observations, which are judgment rather than math.
function buildPcoReport({ data, results, observations, reference }) {
  const p = data.pco;
  const critical = results.filter(r => r.critical && r.status === 'FAIL');
  const mathErrors = results.filter(r => !r.critical && r.status === 'FAIL');
  const warnings = results.filter(r => r.status === 'SKIPPED');
  const cleanBill = results.filter(r => r.status === 'PASS');

  const total = critical.length + mathErrors.length;
  let plainEnglish = `This ${p.isAllowance ? 'allowance ' : ''}change order requests ${money(p.totalAmount)}.`;
  plainEnglish += total === 0
    ? ' The math and contract checks found no issues.'
    : ` ${total} issue${total === 1 ? '' : 's'} found${critical.length ? ` (${critical.length} need${critical.length === 1 ? 's' : ''} resolving before approval)` : ''}.`;
  if (reference?.number) {
    plainEnglish += ` It cites ${reference.type || 'reference'} ${reference.number}.`;
  }

  const header = {
    pcoNumber: p.pcoNumber || 'Not specified',
    title: p.title || null,
    contractor: p.contractor || 'Not specified',
    date: p.date || 'Not specified',
    totalAmount: p.totalAmount,
    isAllowance: !!p.isAllowance,
    reference: reference ? { type: reference.type, number: reference.number, subject: reference.subject } : null,
  };

  const markdown = renderMarkdown({ header, plainEnglish, critical, mathErrors, warnings, cleanBill, observations, reference });
  return { header, plainEnglish, critical, mathErrors, warnings, cleanBill, observations, markdown };
}

function renderMarkdown({ header, plainEnglish, critical, mathErrors, warnings, cleanBill, observations, reference }) {
  const lines = [];
  lines.push(`# Change Order Review — PCO ${header.pcoNumber}${header.title ? `: ${header.title}` : ''}`);
  lines.push('');
  lines.push('> The math and contract checks below are computed from the figures on the documents. The review notes further down are the AI\'s reading of the documents — treat those as prompts to verify, not verdicts.');
  lines.push('');
  lines.push(`**Submitted by:** ${header.contractor}  `);
  lines.push(`**Date:** ${header.date}  `);
  lines.push(`**Amount requested:** ${money(header.totalAmount)}  `);
  if (header.isAllowance) lines.push('**Presented as:** Allowance  ');
  if (header.reference?.number) lines.push(`**Generated by:** ${header.reference.type || ''} ${header.reference.number}${header.reference.subject ? ` — ${header.reference.subject}` : ''}  `);
  lines.push('');
  lines.push(`**Summary:** ${plainEnglish}`);
  lines.push('');

  const section = (title, items, emptyText) => {
    lines.push(`## ${title}`);
    lines.push('');
    if (items.length === 0) {
      lines.push(emptyText);
    } else {
      for (const r of items) {
        lines.push(`- **${r.description}**`);
        lines.push(`  ${r.detail}`);
      }
    }
    lines.push('');
  };

  section('Issues to Resolve Before Approving', critical, '_None._');
  section('Other Problems Found', mathErrors, '_None._');

  const notes = [];
  if (reference && observations?.scopeAlignment?.notes) {
    notes.push({ title: 'Does the price match what was asked for?', body: observations.scopeAlignment.notes });
  }
  if (observations?.lumpSumConcerns) {
    notes.push({ title: 'Lump sums worth a closer look', body: observations.lumpSumConcerns });
  }
  if (observations?.pricingSanity) {
    notes.push({ title: 'Pricing worth double-checking', body: observations.pricingSanity });
  }
  lines.push('## Review Notes — the AI\'s read, verify before acting');
  lines.push('');
  if (notes.length === 0) {
    lines.push('_Nothing stood out beyond the checks above._');
  } else {
    for (const n of notes) {
      lines.push(`- **${n.title}**`);
      lines.push(`  ${n.body}`);
    }
  }
  lines.push('');

  section('Checks We Couldn\'t Fully Complete', warnings, '_None._');
  section('Everything Else Checked Out Fine', cleanBill, '_None passed._');

  return lines.join('\n');
}

module.exports = { buildPcoReport };
